# Generated by Django 4.2.3 on 2023-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentospendentes',
            name='assunto',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='atendimentospendentes',
            name='status',
            field=models.CharField(choices=[('p', 'pendente'), ('r', 'respondida')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='atendimentospendentes',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
