# Generated by Django 4.2.3 on 2023-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="account",
            name="cpf",
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="account",
            name="data_nascimento",
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
