# Generated by Django 4.2.3 on 2023-08-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='account',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
