# Generated by Django 4.2.3 on 2023-08-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_account_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
