# Generated by Django 4.2.3 on 2023-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_pedido_pedido_status_id_and_more'),
        ('usuarios', '0011_adress_paymenttype_userpaymentmethod_useradress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradress',
            name='adress_id',
        ),
        migrations.RemoveField(
            model_name='useradress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='paymentype_id',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='user_id',
        ),
        migrations.AddField(
            model_name='atendimentos',
            name='phone',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='userAdress',
        ),
        migrations.DeleteModel(
            name='UserPaymentMethod',
        ),
    ]
