# Generated by Django 4.2.3 on 2023-08-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_useradress_adress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='is_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
