# Generated by Django 4.2.3 on 2023-08-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_account_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superadmin',
        ),
    ]
