# Generated by Django 4.2.3 on 2023-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_emailerrorslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
