# Generated by Django 4.2.3 on 2023-08-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_usercart_usercartitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercartitems',
            options={'verbose_name_plural': 'Items Carrinho'},
        ),
        migrations.RenameField(
            model_name='usercartitems',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
