# Generated by Django 4.2.3 on 2023-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usercartitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentos',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('r', 'Respondida')], default='p', max_length=1),
        ),
    ]
