# Generated by Django 4.2.3 on 2023-08-06 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loja.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_adress_paymenttype_userpaymentmethod_useradress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=None, max_length=15, null=True)),
                ('entregue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_stock', models.IntegerField(default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default=None, max_length=30, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VariationsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(default=None, max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='setor',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to=loja.funcs.product_image_path),
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variations_options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.variationsoptions')),
            ],
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=None, null=True)),
                ('produtoItem_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.produtoitem')),
                ('user_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usercart')),
            ],
        ),
        migrations.AddField(
            model_name='produtoitem',
            name='produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('pedido_total', models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True)),
                ('pedido_status_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.pedidostatus')),
                ('shiping_method_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.shipingmethod')),
                ('shipping_adress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.userpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, null=True, unique=True)),
                ('variations', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.variations')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.category'),
        ),
    ]
