# Generated by Django 4.2.3 on 2023-08-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedidostatus_produtoitem_shipingmethod_usercart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_status_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='shiping_method_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='shipping_adress',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='produtoitem',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='produtoItem_id',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='user_cart_id',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='variations_options_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoStatus',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ProdutoItem',
        ),
        migrations.DeleteModel(
            name='ShipingMethod',
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
        migrations.DeleteModel(
            name='UserItems',
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
        migrations.DeleteModel(
            name='VariationsOptions',
        ),
    ]
