# Generated by Django 4.2.3 on 2023-08-09 15:23

from django.db import migrations, models
import loja.funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0003_remove_pedido_pedido_status_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Produto', max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao', models.TextField()),
                ('img', models.ImageField(upload_to=loja.funcs.product_image_path)),
            ],
        ),
    ]
