# Generated by Django 4.2.3 on 2023-08-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_remove_usercartitems_cart_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TosaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.tosatype')),
            ],
        ),
    ]
