# Generated by Django 4.2.3 on 2023-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_tosa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosatype',
            name='animal',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
