# Generated by Django 4.2.3 on 2023-08-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_tosatype_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='porte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tosatype',
            name='animal',
        ),
        migrations.AddField(
            model_name='tosatype',
            name='porte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.porte'),
        ),
    ]
