# Generated by Django 4.2.3 on 2023-08-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_porte_remove_tosatype_animal_tosatype_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosa',
            name='pet',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
