# Generated by Django 4.2.3 on 2023-08-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0015_tosa_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tosa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tosa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BanhoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('preco', models.FloatField()),
                ('porte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.porte')),
            ],
        ),
        migrations.CreateModel(
            name='Banho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default=None, max_length=30, null=True)),
                ('data', models.DateTimeField(unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.banhotype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
