# Generated by Django 4.2.3 on 2023-08-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_alter_tosa_user_banhotype_banho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banhotype',
            options={'verbose_name_plural': 'Categorias Banhos'},
        ),
    ]
