# Generated by Django 4.2.3 on 2023-08-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_alter_banhotype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banhotype',
            options={'verbose_name_plural': 'Categorias Banho'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias Produtos'},
        ),
        migrations.AlterModelOptions(
            name='tosatype',
            options={'verbose_name_plural': 'Categorias Tosa'},
        ),
    ]
