# Generated by Django 4.2.3 on 2023-08-15 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_rename_pet_name_banho_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='banho',
            name='marcado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tosa',
            name='marcado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
